// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WatchSync.Api.Data;

#nullable disable

namespace WatchSync.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WatchSync.Api.Models.Show", b =>
                {
                    b.Property<int>("ShowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShowId"));

                    b.Property<int>("AddedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentEpisode")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalEpisodes")
                        .HasColumnType("integer");

                    b.Property<int>("WatchPartyId")
                        .HasColumnType("integer");

                    b.HasKey("ShowId");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("WatchPartyId");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("WatchSync.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WatchSync.Api.Models.WatchEntry", b =>
                {
                    b.Property<int>("WatchEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WatchEntryId"));

                    b.Property<int>("PartyTurnCountAfter")
                        .HasColumnType("integer");

                    b.Property<int>("ShowId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("WatchPartyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("WatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WatchEntryId");

                    b.HasIndex("ShowId");

                    b.HasIndex("UserId");

                    b.HasIndex("WatchPartyId");

                    b.ToTable("WatchEntries");
                });

            modelBuilder.Entity("WatchSync.Api.Models.WatchParty", b =>
                {
                    b.Property<int>("WatchPartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WatchPartyId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentTurnCount")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentTurnOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TurnLimit")
                        .HasColumnType("integer");

                    b.HasKey("WatchPartyId");

                    b.ToTable("WatchParties");
                });

            modelBuilder.Entity("WatchSync.Api.Models.WatchPartyMember", b =>
                {
                    b.Property<int>("WatchPartyMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WatchPartyMemberId"));

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TurnOrder")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("WatchPartyId")
                        .HasColumnType("integer");

                    b.HasKey("WatchPartyMemberId");

                    b.HasIndex("UserId");

                    b.HasIndex("WatchPartyId");

                    b.ToTable("WatchPartyMembers");
                });

            modelBuilder.Entity("WatchSync.Api.Models.Show", b =>
                {
                    b.HasOne("WatchSync.Api.Models.User", "AddedByUser")
                        .WithMany("Shows")
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchSync.Api.Models.WatchParty", "WatchParty")
                        .WithMany("Shows")
                        .HasForeignKey("WatchPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("WatchParty");
                });

            modelBuilder.Entity("WatchSync.Api.Models.WatchEntry", b =>
                {
                    b.HasOne("WatchSync.Api.Models.Show", "Show")
                        .WithMany()
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchSync.Api.Models.User", "User")
                        .WithMany("WatchEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchSync.Api.Models.WatchParty", "WatchParty")
                        .WithMany("WatchEntries")
                        .HasForeignKey("WatchPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");

                    b.Navigation("User");

                    b.Navigation("WatchParty");
                });

            modelBuilder.Entity("WatchSync.Api.Models.WatchPartyMember", b =>
                {
                    b.HasOne("WatchSync.Api.Models.User", "User")
                        .WithMany("WatchPartyMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchSync.Api.Models.WatchParty", "WatchParty")
                        .WithMany("WatchPartyMembers")
                        .HasForeignKey("WatchPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WatchParty");
                });

            modelBuilder.Entity("WatchSync.Api.Models.User", b =>
                {
                    b.Navigation("Shows");

                    b.Navigation("WatchEntries");

                    b.Navigation("WatchPartyMembers");
                });

            modelBuilder.Entity("WatchSync.Api.Models.WatchParty", b =>
                {
                    b.Navigation("Shows");

                    b.Navigation("WatchEntries");

                    b.Navigation("WatchPartyMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
